import getCurrentUser from '@client/libs/server/getCurrentUser';
import { cookies } from 'next/headers';
import { ReactNode } from 'react';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};
type PropsType = {
  children: ReactNode | ReactNode[];
};
export default async function Layout({ children }: PropsType) {
  const user = await getCurrentUser();
  const cookieStore = cookies();
  const token = cookieStore.has('token');
  return <main>{children}</main>;
}
