import Header2 from '@client/components/ui/Header2';
import getRoleDetails from '@client/libs/server/getRoleDetails';
import getSpaceDetails from '@client/libs/server/getSpaceDetails';
import Link from 'next/link';
import { ReactNode } from 'react';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};
type PropsType = {
  children: ReactNode | ReactNode[];
  params: { roleId: string };
};
export default async function Layout({ children, params }: PropsType) {
  const role = await getRoleDetails(params.roleId);
  return (
    <main className="flex flex-col h-full w-full  px-1 md:px-2 lg:px-4 ">
      <div className=" w-full  border-b border-secondary-500 my-4">
        <div className="flex gap-2 items-center my-2">
          <Header2 title={role.name} />
        </div>
      </div>
      <div className="">{children}</div>
    </main>
  );
}
