import AdminSidebar from '@client/components/Sidebar/AdminSidebar';
import getServerUser from '@client/libs/server/getServerUser';
import { cookies } from 'next/headers';
import { ReactNode } from 'react';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};
type PropsType = {
  children: ReactNode | ReactNode[];
};
export default async function Layout({ children }: PropsType) {
  const user = await getServerUser();
  const cookieStore = cookies();
  const token = cookieStore.has('token');
  return (
    <main className="flex gap-2 h-full">
      <AdminSidebar />
      <section className="w-full px-4 py-4 mx-auto">{children}</section>
    </main>
  );
}
