import getCurrentUser from '@client/libs/server/getCurrentUser';
import { getUserAccessRoles } from '@libs/utils/getUserAccessRoles';
import { RoleCode, RoleScop } from '@prisma/client';
import { redirect } from 'next/navigation';
import { ReactNode } from 'react';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};
type PropsType = {
  children: ReactNode | ReactNode[];
  params: { spaceName: string };
};
export default async function Layout({ children, params }: PropsType) {
  const user = await getCurrentUser();
  if (!user) {
    return redirect('/auth/login');
  }
  const userRoles = getUserAccessRoles(user.roles, [
    { scop: RoleScop.SUPER, code: RoleCode.ADMIN },
    { scop: RoleScop.SUPER, code: RoleCode.EDITOR },
    { scop: RoleScop.SPACE, code: RoleCode.ADMIN, spaceName: params.spaceName },
    {
      scop: RoleScop.SPACE,
      code: RoleCode.EDITOR,
      spaceName: params.spaceName,
    },
  ]);
  if (!userRoles.length) {
    return redirect('/auth/login');
  }
  return <main className="flex h-full w-full">{children}</main>;
}
