import Footer from '@client/components/Footer';
import { ReactNode } from 'react';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};
type PropsType = {
  children: ReactNode | ReactNode[];
};
export default async function Layout({ children }: PropsType) {
  return (
    <>
      {children}
      <Footer />
    </>
  );
}
