import Navbar from '@client/components/Navbar';
import StoreProvider from '@client/libs/app/StoreProvider';
import getCurrentUser from '@client/libs/server/getCurrentUser';
import { Roboto } from 'next/font/google';
import { cookies } from 'next/headers';
import { ReactNode } from 'react';
import './globals.css';

// const inter = Inter({ subsets: ["latin"] });
const roboto = Roboto({
  subsets: ['greek'],
  weight: ['400'],
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};
type PropsType = {
  children: ReactNode | ReactNode[];
};
export default async function RootLayout({ children }: PropsType) {
  const user = await getCurrentUser();
  const cookieStore = cookies();
  const token = cookieStore.has('token')
    ? (cookieStore.get('token')?.value as string)
    : undefined;

  return (
    <html className="dark" lang="en">
      <body
        className={`${roboto.className} bg-secondary-50 dark:bg-secondary-950 text-slate-800 dark:text-slate-200`}
      >
        <StoreProvider user={user} token={token}>
          <Navbar />
          {children}
        </StoreProvider>
      </body>
    </html>
  );
}
